web/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/homepage'
  post 'report/reports'
  resources :articles
  get 'report/index'
  get 'report/homepage'
  root 'welcome#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web/app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
end

web/app/models/report.rb
# report class
class Report < ApplicationRecord
  def rep
  end
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

web/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    @reports = Report.all
  end
  def edit
    @article = Article.find(params[:id])
  end
  def show
    @article = Article.find(params[:id])
  end
  def new
      @article = Article.new
  end
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

web/app/controllers/report_controller.rb
# class controller
class ReportController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @reports = Report.all
  end

  def reports
    # puts(request.raw_post)
    # JSON PARSE
    # future for slack report
    @report = Report.new(body: request.raw_post)
    @report.save
    render json: JSON.pretty_generate(@report), status: :ok
  end
end

web/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
    @reports = Report.all
  end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/articles_helper.rb
module ArticlesHelper
end

web/app/helpers/report_helper.rb
# module helps
module ReportHelper
  # pass report , or extract reports
  def extract_source(body)
    values = JSON.parse(body)
    raise 'missing csp-report' unless values.key? 'csp-report'

    raise 'missing document-uri' unless values['csp-report'].key? 'document-uri'

    values['csp-report']['document-uri']
  end

  # violation
  def extract_violation(body)
    values = JSON.parse(body)
    raise 'missing csp-report' unless values.key? 'csp-report'

    raise 'missing violated-directive' unless
      values['csp-report'].key? 'violated-directive'

    values['csp-report']['violated-directive']
  end

  # blocked-uri
  def extract_blocked_uri(body)
    values = JSON.parse(body)
    raise 'missing csp-report' unless values.key? 'csp-report'

    raise 'missing blocked-uri' unless values['csp-report'].key? 'blocked-uri'

    values['csp-report']['blocked-uri']
  end

  def print_id_and_key(values, val)
    id = val
    key = values[val]
    "#{id}: #{key}"
  end
end

web/app/helpers/welcome_helper.rb
# module helper
module WelcomeHelper
end

web/app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

web/app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

web/app/views/articles/index.html.erb
<%= link_to 'New Article', new_article_path %>
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
       <td><%= link_to 'Edit', edit_article_path(article) %></td>
    </tr>
  <% end %>
  
</table>
<%= link_to 'Back', articles_path %>

web/app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>

<%= link_to 'Back', articles_path %>

web/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

web/app/views/welcome/homepage.html.erb
<h1>The following are the reported violations:</h1>
<table class ="table ">
  <tr>
    <th>Document Source</th>
    <th>Violated directive</th>
    <th>Blocked URI </th>
    <th>Details </th>
  </tr>
  <% @reports.each_with_index do |report, index| %>
  <tr>
    <td> <%= extract_source(report.body) %> </td>
    <td><%= extract_violation(report.body) %></td>
    <td><%= extract_blocked_uri(report.body) %></td>
    <td> <%= index %> <td>
    <td>
      <button class="expand" id="expand_<%=index %>" value="expand" onclick="main(<%= index %>)">
        expand
      </button>
      <a class="expand-content-show">
        <% values = JSON.parse(report.body) %>
          <% if values.key? 'csp-report' %>
            <% values['csp-report'].each do|val| %>
              <%= print_id_and_key(values['csp-report'], val) %>
            <% end %>
          <% end %>
      </a>
    </td>
  </tr>
  <% end %>

</table>